package routes

import (
	"github.com/gofiber/fiber/v2"

	"PenbunAPI/controllers"
	"PenbunAPI/middleware"
)

func SetupV1Routes(app *fiber.App, jwtSecret string) {
	protected := app.Group("/api/v1/protected", middleware.JWTMiddleware(jwtSecret))

	customer := protected.Group("/customer")
	customer.Get("/all", controllers.SelectAllCustomer)
	customer.Get("/page", controllers.SelectPageCustomer)
	customer.Get("/select/id/:id", controllers.SelectCustomerByID)
	customer.Get("/select/name/:name", controllers.SelectCustomerByName)
	customer.Post("/insert", controllers.InsertCustomer)
	customer.Put("/update/:id", controllers.UpdateCustomerByID)
	customer.Put("/delete/:id", controllers.DeleteCustomerByID)
	customer.Delete("/remove/:id", controllers.RemoveCustomerByID)

	customerType := protected.Group("/customer-type")
	customerType.Get("/all", controllers.SelectAllCustomerType)
	customerType.Get("/page", controllers.SelectPageCustomerType)
	customerType.Get("/select/id/:id", controllers.SelectCustomerTypeByID)
	customerType.Get("/select/name/:name", controllers.SelectCustomerTypeByName)
	customerType.Post("/insert", controllers.InsertCustomerType)
	customerType.Put("/update/:id", controllers.UpdateCustomerTypeByID)
	customerType.Put("/delete/:id", controllers.DeleteCustomerTypeByID)
	customerType.Delete("/remove/:id", controllers.RemoveCustomerTypeByID)

	vendor := protected.Group("/vendor")
	vendor.Get("/all", controllers.SelectAllVendor)
	vendor.Get("/page", controllers.SelectPageVendor)
	vendor.Get("/select/id/:id", controllers.SelectVendorByID)
	vendor.Get("/select/name/:name", controllers.SelectVendorByName)
	vendor.Post("/insert", controllers.InsertVendor)
	vendor.Put("/update/:id", controllers.UpdateVendorByID)
	vendor.Put("/delete/:id", controllers.DeleteVendorByID)
	vendor.Delete("/remove/:id", controllers.RemoveVendorByID)

	vendorType := protected.Group("/vendor-type")
	vendorType.Get("/all", controllers.SelectAllVendorType)
	vendorType.Get("/page", controllers.SelectPageVendorType)
	vendorType.Get("/select/id/:id", controllers.SelectVendorTypeByID)
	vendorType.Get("/select/name/:name", controllers.SelectVendorTypeByName)
	vendorType.Post("/insert", controllers.InsertVendorType)
	vendorType.Put("/update/:id", controllers.UpdateVendorTypeByID)
	vendorType.Put("/delete/:id", controllers.DeleteVendorTypeByID)
	vendorType.Delete("/remove/:id", controllers.RemoveVendorTypeByID)

	book := protected.Group("/book")
	book.Get("/all", controllers.SelectAllBook)
	book.Get("/page", controllers.SelectPageBook)
	book.Get("/select/id/:id", controllers.SelectBookByID)
	book.Get("/select/name/:name", controllers.SelectBookByName)
	book.Post("/insert", controllers.InsertBook)
	book.Put("/update/:id", controllers.UpdateBookByID)
	book.Put("/delete/:id", controllers.DeleteBookByID)
	book.Delete("/remove/:id", controllers.RemoveBookByID)

	bookType := protected.Group("/book-type")
	bookType.Get("/all", controllers.SelectAllBookType)
	bookType.Get("/page", controllers.SelectPageBookType)
	bookType.Get("/select/id/:id", controllers.SelectBookTypeByID)
	bookType.Get("/select/name/:name", controllers.SelectBookTypeByName)
	bookType.Post("/insert", controllers.InsertBookType)
	bookType.Put("/update/:id", controllers.UpdateBookTypeByID)
	bookType.Put("/delete/:id", controllers.DeleteBookTypeByID)
	bookType.Delete("/remove/:id", controllers.RemoveBookTypeByID)

	discount := protected.Group("/discount")
	discount.Get("/all", controllers.SelectAllDiscount)
	discount.Get("/page", controllers.SelectPageDiscount)
	discount.Get("/select/id/:id", controllers.SelectDiscountByID)
	discount.Get("/select/name/:name", controllers.SelectDiscountByName)
	discount.Post("/insert", controllers.InsertDiscount)
	discount.Put("/update/:id", controllers.UpdateDiscountByID)
	discount.Put("/delete/:id", controllers.DeleteDiscountByID)
	discount.Delete("/remove/:id", controllers.RemoveDiscountByID)

	discountType := protected.Group("/discount-type")
	discountType.Get("/all", controllers.SelectAllDiscountType)
	discountType.Get("/page", controllers.SelectPageDiscountType)
	discountType.Get("/select/id/:id", controllers.SelectDiscountTypeByID)
	discountType.Get("/select/name/:name", controllers.SelectDiscountTypeByName)
	discountType.Post("/insert", controllers.InsertDiscountType)
	discountType.Put("/update/:id", controllers.UpdateDiscountTypeByID)
	discountType.Put("/delete/:id", controllers.DeleteDiscountTypeByID)
	discountType.Delete("/remove/:id", controllers.RemoveDiscountTypeByID)

	productFormatType := protected.Group("/product-format-type")
	productFormatType.Get("/all", controllers.SelectAllProductFormatType)
	productFormatType.Get("/page", controllers.SelectPageProductFormatType)
	productFormatType.Get("/select/id/:id", controllers.SelectProductFormatTypeByID)
	productFormatType.Get("/select/name/:name", controllers.SelectProductFormatTypeByName)
	productFormatType.Post("/insert", controllers.InsertProductFormatType)
	productFormatType.Put("/update/:id", controllers.UpdateProductFormatTypeByID)
	productFormatType.Put("/delete/:id", controllers.DeleteProductFormatTypeByID)
	productFormatType.Delete("/remove/:id", controllers.RemoveProductFormatTypeByID)

	productCategory := protected.Group("/product-category")
	productCategory.Get("/all", controllers.SelectAllProductCategory)
	productCategory.Get("/page", controllers.SelectPageProductCategory)
	productCategory.Get("/select/id/:id", controllers.SelectProductCategoryByID)
	productCategory.Get("/select/name/:name", controllers.SelectProductCategoryByName)
	productCategory.Post("/insert", controllers.InsertProductCategory)
	productCategory.Put("/update/:id", controllers.UpdateProductCategoryByID)
	productCategory.Put("/delete/:id", controllers.DeleteProductCategoryByID)
	productCategory.Delete("/remove/:id", controllers.RemoveProductCategoryByID)

	productGroup := protected.Group("/product-group")
	productGroup.Get("/all", controllers.SelectAllProductGroup)
	productGroup.Get("/page", controllers.SelectPageProductGroup)
	productGroup.Get("/select/id/:id", controllers.SelectProductGroupByID)
	productGroup.Get("/select/name/:name", controllers.SelectProductGroupByName)
	productGroup.Post("/insert", controllers.InsertProductGroup)
	productGroup.Put("/update/:id", controllers.UpdateProductGroupByID)
	productGroup.Put("/delete/:id", controllers.DeleteProductGroupByID)
	productGroup.Delete("/remove/:id", controllers.RemoveProductGroupByID)

	unitType := protected.Group("/unit-type")
	unitType.Get("/all", controllers.SelectAllUnitType)
	unitType.Get("/page", controllers.SelectPageUnitType)
	unitType.Get("/select/id/:id", controllers.SelectUnitTypeByID)
	unitType.Get("/select/name/:name", controllers.SelectUnitTypeByName)
	unitType.Post("/insert", controllers.InsertUnitType)
	unitType.Put("/update/:id", controllers.UpdateUnitTypeByID)
	unitType.Put("/delete/:id", controllers.DeleteUnitTypeByID)
	unitType.Delete("/remove/:id", controllers.RemoveUnitTypeByID)

	warehouse := protected.Group("/warehouse")
	warehouse.Get("/all", controllers.SelectAllWarehouse)
	warehouse.Get("/page", controllers.SelectPageWarehouse)
	warehouse.Get("/select/id/:id", controllers.SelectWarehouseByID)
	warehouse.Get("/select/name/:name", controllers.SelectWarehouseByName)
	warehouse.Post("/insert", controllers.InsertWarehouse)
	warehouse.Put("/update/:id", controllers.UpdateWarehouseByID)
	warehouse.Put("/delete/:id", controllers.DeleteWarehouseByID)
	warehouse.Delete("/remove/:id", controllers.RemoveWarehouseByID)

	product := protected.Group("/product")
	product.Get("/all", controllers.SelectAllProduct)
	product.Get("/page", controllers.SelectPageProduct)
	product.Get("/select/id/:id", controllers.SelectProductByID)
	product.Get("/select/name/:name", controllers.SelectProductByName)
	product.Post("/insert", controllers.InsertProduct)
	product.Put("/update/:id", controllers.UpdateProductByID)
	product.Put("/delete/:id", controllers.DeleteProductByID)
	product.Delete("/remove/:id", controllers.RemoveProductByID)
}
